
events {
    worker_connections 1024;
}

http{
server {
    listen 80;

    server_name modern-world.shop;

    location /.well-known/acme-challenge/ {
        allow all;
        root var/www/certbot;
    }
}

#  server {
#         listen 443 ssl;
#         server_name 도메인.com; # 도메인 이름 ex:) eomjunsick.com

#         ssl_certificate /etc/letsencrypt/live/도메인.com/fullchain.pem; # SSL 인증서 경로
#         ssl_certificate_key /etc/letsencrypt/live/도메인.com/privkey.pem; # 개인 키 파일 경로

#         access_log /var/log/nginx/access.log; # 로그 파일 경로
#         error_log /var/log/nginx/error.log; # 에러 로그 파일 경로

#         location / {
#             proxy_pass http://컨테이너서비스이름:3000; # http://[container_name]:[port] 
#         }
#     }

}