import type { Metadata } from 'next';
import StyledComponentsRegistry from './lib/registry';
import { ClientOnly } from '@/utils/clientOnly';
import NotificationComponent from '@/components/notification/NotificationComponent';
import { IMAGE } from '@/utils/image';
import localFont from 'next/font/local';
import GlobalStyleWrapper from './globalStyles';

export const metadata: Metadata = {
  title: '모던월드',
  description: 'Generated by create next app',
  icons: IMAGE.favicon,
};

const neoDGM = localFont({
  src: '../../public/fonts/neodgm.ttf',
  variable: '--font-neodgm',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={neoDGM.variable}>
      <body>
        <StyledComponentsRegistry>
          <GlobalStyleWrapper>{children}</GlobalStyleWrapper>
          <ClientOnly>
            <NotificationComponent />
          </ClientOnly>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
