import type { Metadata } from 'next';
import StyledComponentsRegistry from './lib/registry';
import { ClientOnly } from '@/utils/clientOnly';
import NotificationComponent from '@/components/notification/NotificationComponent';
import { IMAGE } from '@/utils/image';
import GlobalStyleWrapper from './globalStyles';
import '../style/globals.css';

export const metadata: Metadata = {
  title: '모던월드',
  description: 'Generated by create next app',
  icons: IMAGE.favicon,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <StyledComponentsRegistry>
          <GlobalStyleWrapper>{children}</GlobalStyleWrapper>
          <ClientOnly>
            <NotificationComponent />
          </ClientOnly>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
