import type { Metadata } from 'next';
import StyledComponentsRegistry from './lib/registry';
import { ClientOnly } from '@/utils/clientOnly';
import NotificationComponent from '@/components/notification/NotificationComponent';

export const metadata: Metadata = {
  title: '모던월드',
  description: 'Generated by create next app',
  icons: 'https://wang0514.s3.ap-northeast-2.amazonaws.com/page/favicon11.png',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <StyledComponentsRegistry>
          {children}
          <ClientOnly>
            <NotificationComponent />
          </ClientOnly>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
