export const IMAGE = {
  heart: `${process.env.NEXT_PUBLIC_S3}/page/heartPicture.png`,
  rightArrow: `${process.env.NEXT_PUBLIC_S3}/page/Arrow/ArrowRight.png`,
  leftArrow: `${process.env.NEXT_PUBLIC_S3}/page/Arrow/ArrowLeft.png`,
  magnifier: `${process.env.NEXT_PUBLIC_S3}/page/%EB%8F%8B%EB%B3%B4%EA%B8%B0`,
  exit: `${process.env.NEXT_PUBLIC_S3}/page/exit.png`,
  catVillageLogo: `${process.env.NEXT_PUBLIC_S3}/page/villageLogo/catVillageLogo.png`,
  dogVillageLogo: `${process.env.NEXT_PUBLIC_S3}/page/villageLogo/%EA%B0%95%EC%95%84%EC%A7%80+%EB%A7%88%EC%9D%84.png`,
  pencil: `${process.env.NEXT_PUBLIC_S3}/page/%EC%97%B0%ED%95%84.png`,
  comment: `${process.env.NEXT_PUBLIC_S3}/page/previewpage/addComment.png`,
  remove: `${process.env.NEXT_PUBLIC_S3}/page/remove.png`,
  trashBox: `${process.env.NEXT_PUBLIC_S3}/page/trash.png`,
  addFriend: `${process.env.NEXT_PUBLIC_S3}/page/previewpage/addFriend.png`,
  mainLogo: `${process.env.NEXT_PUBLIC_S3}/page/mainLogo.png`,
  powerBtn: `${process.env.NEXT_PUBLIC_S3}/page/power.png`,
  naverLogo: `${process.env.NEXT_PUBLIC_S3}/page/%EB%A1%9C%EA%B7%B8%EC%9D%B8+%EC%95%84%EC%9D%B4%EC%BD%98+%EB%A1%9C%EA%B3%A0+%EB%AA%A8%EC%9D%8C/n%EB%A1%9C%EA%B3%A0-removebg-preview.png`,
  kakaoLogo: `${process.env.NEXT_PUBLIC_S3}/page/%EB%A1%9C%EA%B7%B8%EC%9D%B8+%EC%95%84%EC%9D%B4%EC%BD%98+%EB%A1%9C%EA%B3%A0+%EB%AA%A8%EC%9D%8C/%EC%B9%B4%EC%B9%B4%EC%98%A4%EB%A1%9C%EA%B3%A0-removebg-preview.png`,
  googleLogo: `${process.env.NEXT_PUBLIC_S3}/page/%EB%A1%9C%EA%B7%B8%EC%9D%B8+%EC%95%84%EC%9D%B4%EC%BD%98+%EB%A1%9C%EA%B3%A0+%EB%AA%A8%EC%9D%8C/%EA%B5%AC%EA%B8%80%EB%A1%9C%EA%B3%A02-removebg-preview.png`,
  firstDog: `${process.env.NEXT_PUBLIC_S3}/items/%EC%BA%90%EB%A6%AD%ED%84%B0%EB%AA%A8%EC%9D%8C/%EC%8B%9C%EC%9E%91%EA%B0%95%EC%95%84%EC%A7%80.svg`,
  firstCat: `${process.env.NEXT_PUBLIC_S3}/items/%EC%BA%90%EB%A6%AD%ED%84%B0%EB%AA%A8%EC%9D%8C/%EC%8B%9C%EC%9E%91%EA%B3%A0%EC%96%91%EC%9D%B4.svg`,
  warning: `${process.env.NEXT_PUBLIC_S3}/page/warning-icon.svg`,
  cross: `${process.env.NEXT_PUBLIC_S3}/page/cross-small_4338828.svg`,
  favicon: `${process.env.NEXT_PUBLIC_S3}/page/favicon11.png`,
};
